//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account_Type_OfflineTable
    {
        public Account_Type_OfflineTable()
        {
            this.User_Details_OfflineTable = new HashSet<User_Details_OfflineTable>();
        }
    
        public int iA_Tid { get; set; }
        public string vcType { get; set; }
    
        public virtual ICollection<User_Details_OfflineTable> User_Details_OfflineTable { get; set; }
    }
}
