//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank_Details
    {
        public Bank_Details()
        {
            this.User_Bank_Details = new HashSet<User_Bank_Details>();
        }
    
        public int iB_Did { get; set; }
        public string vcBankName { get; set; }
        public string vcBankHqLocation { get; set; }
        public string vcBankPhoneNo { get; set; }
        public string vcBankEmail { get; set; }
    
        public virtual ICollection<User_Bank_Details> User_Bank_Details { get; set; }
    }
}
