//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buyer_Details_OfflineTable
    {
        public int iB_Did { get; set; }
        public int iFKBuyer_DetailsId { get; set; }
        public double dDataBought { get; set; }
        public double dDataUsed { get; set; }
        public bool iHasExpired { get; set; }
    
        public virtual User_Details_OfflineTable User_Details_OfflineTable { get; set; }
    }
}
