//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connect.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConnectPersonalServerEntities : DbContext
    {
        public ConnectPersonalServerEntities()
            : base("name=ConnectPersonalServerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account_Type> Account_Type { get; set; }
        public DbSet<Bank_Details> Bank_Details { get; set; }
        public DbSet<Buyer_Details> Buyer_Details { get; set; }
        public DbSet<Data_Usage_Log> Data_Usage_Log { get; set; }
        public DbSet<Sellers_Login> Sellers_Login { get; set; }
        public DbSet<User_Bank_Details> User_Bank_Details { get; set; }
        public DbSet<User_Details> User_Details { get; set; }
        public DbSet<Withrawal_Table> Withrawal_Table { get; set; }
    }
}
