//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sellers_Login_OfflineTable
    {
        public int iS_Lid { get; set; }
        public int iFKUser_DetailsId { get; set; }
        public double dDataSizeAsAtTimeOfUpload { get; set; }
        public double dDataUsedByCustomers { get; set; }
        public bool iHasExpired { get; set; }
    
        public virtual User_Details_OfflineTable User_Details_OfflineTable { get; set; }
    }
}
