//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sellers_Login
    {
        public Sellers_Login()
        {
            this.Data_Usage_Log = new HashSet<Data_Usage_Log>();
        }
    
        public int iS_Lid { get; set; }
        public int iFK_User_DetailsId { get; set; }
        public string vcUsername { get; set; }
        public string vcLoginPassword { get; set; }
        public System.DateTime dtDateAddedOrUpdated { get; set; }
        public bool iHasExpired { get; set; }
        public decimal dDataBalance { get; set; }
        public decimal dDataSizeAsAtTimeOfUpload { get; set; }
        public decimal dDataUsedByCustomers { get; set; }
        public bool iIsLoginInUse { get; set; }
    
        public virtual ICollection<Data_Usage_Log> Data_Usage_Log { get; set; }
        public virtual User_Details User_Details { get; set; }
    }
}
