//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Details_OfflineTable
    {
        public User_Details_OfflineTable()
        {
            this.Buyer_Details_OfflineTable = new HashSet<Buyer_Details_OfflineTable>();
            this.Sellers_Login_OfflineTable = new HashSet<Sellers_Login_OfflineTable>();
        }
    
        public int iU_Did { get; set; }
        public int iFK_AccountTypeId { get; set; }
        public string vcFirstName { get; set; }
        public string vcLastName { get; set; }
        public string vcEmail { get; set; }
        public string vcProfilePicturePath { get; set; }
        public string vcAddress { get; set; }
        public string vcCountry { get; set; }
        public string vcState { get; set; }
        public string vcZipCode { get; set; }
    
        public virtual Account_Type_OfflineTable Account_Type_OfflineTable { get; set; }
        public virtual ICollection<Buyer_Details_OfflineTable> Buyer_Details_OfflineTable { get; set; }
        public virtual ICollection<Sellers_Login_OfflineTable> Sellers_Login_OfflineTable { get; set; }
    }
}
