//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Details
    {
        public User_Details()
        {
            this.Buyer_Details = new HashSet<Buyer_Details>();
            this.Data_Usage_Log = new HashSet<Data_Usage_Log>();
            this.Sellers_Login = new HashSet<Sellers_Login>();
            this.Withrawal_Table = new HashSet<Withrawal_Table>();
        }
    
        public int iU_Did { get; set; }
        public string vcFirstName { get; set; }
        public string vcMiddleName { get; set; }
        public string vcLastName { get; set; }
        public string vcEmail { get; set; }
        public string vcPassword { get; set; }
        public string cSex { get; set; }
        public Nullable<System.DateTime> dDOB { get; set; }
        public Nullable<int> iProfilePictureId { get; set; }
        public string vcAddress { get; set; }
        public int iFK_AccountTypeId { get; set; }
    
        public virtual Account_Type Account_Type { get; set; }
        public virtual ICollection<Buyer_Details> Buyer_Details { get; set; }
        public virtual ICollection<Data_Usage_Log> Data_Usage_Log { get; set; }
        public virtual ICollection<Sellers_Login> Sellers_Login { get; set; }
        public virtual ICollection<Withrawal_Table> Withrawal_Table { get; set; }
    }
}
