//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Withrawal_Table
    {
        public int iW_Tid { get; set; }
        public int iFKUser_DetailsId { get; set; }
        public int iUserId { get; set; }
        public decimal mAmountWithrawn { get; set; }
    
        public virtual User_Details User_Details { get; set; }
    }
}
